-- MySQL Script generated by MySQL Workbench
-- Mon Mar 16 18:45:39 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema web_entrenadores
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web_entrenadores
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web_entrenadores` DEFAULT CHARACTER SET utf8mb4 ;
USE `web_entrenadores` ;

-- -----------------------------------------------------
-- Table `web_entrenadores`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_entrenadores`.`usuario` ;

CREATE TABLE IF NOT EXISTS `web_entrenadores`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `passwd_hash` VARCHAR(255) NOT NULL,
  `rol` ENUM('ENTRENADOR', 'CLIENTE') NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_entrenadores`.`entrenador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_entrenadores`.`entrenador` ;

CREATE TABLE IF NOT EXISTS `web_entrenadores`.`entrenador` (
  `id_usuario` INT NOT NULL,
  `especialidad` VARCHAR(80) NULL,
  `bio` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_entrenador_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `web_entrenadores`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_entrenadores`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_entrenadores`.`cliente` ;

CREATE TABLE IF NOT EXISTS `web_entrenadores`.`cliente` (
  `id_usuario` INT NOT NULL,
  `id_entrenador` INT NOT NULL,
  `fecha_alta` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nivel` ENUM('PRINCIPIANTE', 'INTERMEDIO', 'AVANZADO') NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `web_entrenadores`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_entrenador`
    FOREIGN KEY (`id_entrenador`)
    REFERENCES `web_entrenadores`.`entrenador` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_entrenadores`.`metricafisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_entrenadores`.`metricafisica` ;

CREATE TABLE IF NOT EXISTS `web_entrenadores`.`metricafisica` (
  `id_metrica` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `peso_kg` DECIMAL(5,2) NOT NULL,
  `altura_cm` DECIMAL(5,2) NULL,
  `grasa_pct` DECIMAL(5,2) NULL,
  `comentario` VARCHAR(255) NULL,
  PRIMARY KEY (`id_metrica`),
  INDEX `fk_metrica_cliente_idx` (`id_cliente` ASC) VISIBLE,
  UNIQUE INDEX `cliente_registro` (`id_cliente` ASC, `fecha_registro` ASC) VISIBLE,
  CONSTRAINT `fk_metrica_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `web_entrenadores`.`cliente` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_entrenadores`.`rutina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_entrenadores`.`rutina` ;

CREATE TABLE IF NOT EXISTS `web_entrenadores`.`rutina` (
  `id_rutina` INT NOT NULL AUTO_INCREMENT,
  `id_entrenador` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `objetivo` VARCHAR(150) NULL,
  `descripcion` VARCHAR(255) NULL,
  `nivel` ENUM('PRINCIPIANTE', 'INTERMEDIO', 'AVANZADO') NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_rutina`),
  INDEX `fk_rutina_entrenador_idx` (`id_entrenador` ASC) VISIBLE,
  CONSTRAINT `fk_rutina_entrenador`
    FOREIGN KEY (`id_entrenador`)
    REFERENCES `web_entrenadores`.`entrenador` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_entrenadores`.`bloqueRutina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_entrenadores`.`bloqueRutina` ;

CREATE TABLE IF NOT EXISTS `web_entrenadores`.`bloqueRutina` (
  `id_bloque_rutina` INT NOT NULL AUTO_INCREMENT,
  `id_rutina` INT NOT NULL,
  `numero_dia` TINYINT NOT NULL,
  `nombre` VARCHAR(80) NULL,
  `notas` VARCHAR(255) NULL,
  PRIMARY KEY (`id_bloque_rutina`),
  INDEX `fk_bloque_rutina_idx` (`id_rutina` ASC) VISIBLE,
  UNIQUE INDEX `uq_bloquerutina_rutina_dia` (`id_rutina` ASC, `numero_dia` ASC) VISIBLE,
  CONSTRAINT `fk_bloque_rutina`
    FOREIGN KEY (`id_rutina`)
    REFERENCES `web_entrenadores`.`rutina` (`id_rutina`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_entrenadores`.`asignacionRutina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_entrenadores`.`asignacionRutina` ;

CREATE TABLE IF NOT EXISTS `web_entrenadores`.`asignacionRutina` (
  `id_asignacion_rutina` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_rutina` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `estado` ENUM('ACTIVA', 'PAUSADA', 'FINALIZADA') NOT NULL,
  `notas` VARCHAR(255) NULL,
  PRIMARY KEY (`id_asignacion_rutina`),
  INDEX `fk_asignacion_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_asignacion_rutina_idx` (`id_rutina` ASC) VISIBLE,
  UNIQUE INDEX `cliente_rutina_inicio` (`id_cliente` ASC, `id_rutina` ASC, `fecha_inicio` ASC) VISIBLE,
  CONSTRAINT `fk_asignacion_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `web_entrenadores`.`cliente` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignacion_rutina`
    FOREIGN KEY (`id_rutina`)
    REFERENCES `web_entrenadores`.`rutina` (`id_rutina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_entrenadores`.`sesionRutina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_entrenadores`.`sesionRutina` ;

CREATE TABLE IF NOT EXISTS `web_entrenadores`.`sesionRutina` (
  `id_sesion_rutina` INT NOT NULL AUTO_INCREMENT,
  `id_asignacion` INT NULL,
  `id_bloque_rutina` INT NULL,
  `fecha_hora` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `duracion_min` SMALLINT NULL,
  `esfuerzo_rpe` TINYINT NOT NULL,
  `comentario` VARCHAR(255) NULL,
  PRIMARY KEY (`id_sesion_rutina`),
  CONSTRAINT `fk_asignacion_sesion`
    FOREIGN KEY (`id_asignacion`)
    REFERENCES `web_entrenadores`.`asignacionRutina` (`id_asignacion_rutina`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bloque_sesion`
    FOREIGN KEY (`id_bloque_rutina`)
    REFERENCES `web_entrenadores`.`bloqueRutina` (`id_bloque_rutina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_entrenadores`.`ejercicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_entrenadores`.`ejercicio` ;

CREATE TABLE IF NOT EXISTS `web_entrenadores`.`ejercicio` (
  `id_ejercicio` INT NOT NULL AUTO_INCREMENT,
  `id_entrenador` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `grupo_muscular` VARCHAR(50) NULL,
  `equipamiento` VARCHAR(50) NULL,
  `video_url` VARCHAR(255) NULL,
  `fotos_url` VARCHAR(255) NULL,
  `creado_en` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_ejercicio`),
  INDEX `fk_entrenador_ejercicio_idx` (`id_entrenador` ASC) VISIBLE,
  UNIQUE INDEX `uq_ejercicio_entrenador_nombre` (`id_entrenador` ASC, `nombre` ASC) VISIBLE,
  CONSTRAINT `fk_entrenador_ejercicio`
    FOREIGN KEY (`id_entrenador`)
    REFERENCES `web_entrenadores`.`entrenador` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_entrenadores`.`bloqueRutinaEjercicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_entrenadores`.`bloqueRutinaEjercicio` ;

CREATE TABLE IF NOT EXISTS `web_entrenadores`.`bloqueRutinaEjercicio` (
  `id_bloque_rutina_ejercicio` INT NOT NULL AUTO_INCREMENT,
  `id_bloque_rutina` INT NOT NULL,
  `id_ejercicio` INT NOT NULL,
  `orden` TINYINT NOT NULL,
  `reps_plan` TINYINT NOT NULL,
  `series_plan` TINYINT NOT NULL,
  `descanso_seg` SMALLINT NULL,
  `peso_obj` DECIMAL(6,2) NULL,
  `notas` VARCHAR(255) NULL,
  PRIMARY KEY (`id_bloque_rutina_ejercicio`),
  INDEX `fk_bloque_rutina_ejercicio_idx` (`id_bloque_rutina` ASC) VISIBLE,
  INDEX `fk_bre_ejercicio_idx` (`id_ejercicio` ASC) VISIBLE,
  UNIQUE INDEX `uq_bre_bloque_orden` (`id_bloque_rutina` ASC, `orden` ASC) VISIBLE,
  CONSTRAINT `fk_bre_bloquerutina`
    FOREIGN KEY (`id_bloque_rutina`)
    REFERENCES `web_entrenadores`.`bloqueRutina` (`id_bloque_rutina`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bre_ejercicio`
    FOREIGN KEY (`id_ejercicio`)
    REFERENCES `web_entrenadores`.`ejercicio` (`id_ejercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_entrenadores`.`ejercicioRealizado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_entrenadores`.`ejercicioRealizado` ;

CREATE TABLE IF NOT EXISTS `web_entrenadores`.`ejercicioRealizado` (
  `id_ejercicio_realizado` INT NOT NULL AUTO_INCREMENT,
  `id_sesion` INT NOT NULL,
  `id_ejercicio` INT NOT NULL,
  `orden` TINYINT NOT NULL,
  `series_real` TINYINT NOT NULL,
  `reps_real` TINYINT NOT NULL,
  `peso_real` DECIMAL(6,2) NULL,
  `rpe_real` TINYINT NULL,
  `comentario` VARCHAR(255) NULL,
  `distancia_km` DECIMAL(5,2) NULL,
  PRIMARY KEY (`id_ejercicio_realizado`),
  INDEX `fk_sesion_ej_realizado_idx` (`id_sesion` ASC) VISIBLE,
  INDEX `fk_ejercicio_ej_realizado_idx` (`id_ejercicio` ASC) VISIBLE,
  UNIQUE INDEX `uq_ej_realizado_sesion_orden` (`id_sesion` ASC, `orden` ASC) VISIBLE,
  CONSTRAINT `fk_sesion_ej_realizado`
    FOREIGN KEY (`id_sesion`)
    REFERENCES `web_entrenadores`.`sesionRutina` (`id_sesion_rutina`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ejercicio_ej_realizado`
    FOREIGN KEY (`id_ejercicio`)
    REFERENCES `web_entrenadores`.`ejercicio` (`id_ejercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
